# -*- coding: utf-8 -*-
"""Copy of lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3F0jkp6zIL62x7oVquRSjz2dOXBK3sQ
"""

# !unzip -P "I hereby accept the SigComp 2011 disclaimer." /content/Questioned\(1287\).zip -d /content/questioned

# !file /content/Questioned\(1287\).zip

# !unzip Offline\ Forgeries.zip
# !unzip Offline\ Genuine.zip

# from google.colab import drive
# drive.mount('/content/drive')

import torch
import numpy as np
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision
import torchvision.transforms as transforms
import torch.optim as optim
import os
import torch
from torch.utils.data import Dataset
from PIL import Image
import torchvision.transforms as transforms

PATH = './mymodel.pth'



"""DATA"""

genuine_extract_path = '/content/Offline Genuine'
forgery_extract_path = '/content/Offline Forgeries'
print(f"Genuine files: {os.listdir(genuine_extract_path)}")
print(f"Forgery files: {os.listdir(forgery_extract_path)}")

class SignatureVerificationDataset(Dataset):
    def __init__(self, genuine_dir, forgery_dir, transform=None):
        """
        Args:
            genuine_dir (str): Path to offline_genuine folder (e.g., './data/offline_genuine').
            forgery_dir (str): Path to offline_forgeries folder (e.g., './data/offline_forgeries').
            transform (callable, optional): Transformations to apply to images.
        """
        self.genuine_dir = genuine_dir
        self.forgery_dir = forgery_dir
        self.transform = transform
        self.pairs = []
        self.labels = []

        # Dictionary to store signatures by author
        genuine_by_author = {}
        forgery_by_author = {}

        # Load genuine signatures
        for filename in os.listdir(genuine_dir):
            if filename.endswith(('.png', '.jpg', '.jpeg','.PNG')):
                try:
                    # Parse filename, e.g., '001_02.png' -> author '001'
                    author_id = filename.split('_')[0]
                    img_path = os.path.join(genuine_dir, filename)
                    if author_id not in genuine_by_author:
                        genuine_by_author[author_id] = []
                    genuine_by_author[author_id].append(img_path)
                except (ValueError, IndexError):
                    print(f"Skipping invalid genuine filename: {filename}")
                    continue

        # Load forged signatures
        for filename in os.listdir(forgery_dir):
            if filename.endswith(('.png', '.jpg', '.jpeg')):
                try:
                    # Parse filename, e.g., '0119001_01.png' -> author '001'
                    parts = filename.split('_')
                    author_id = parts[0][-3:]  # Extract last 3 digits (e.g., '001' from '0119001')
                    img_path = os.path.join(forgery_dir, filename)
                    if author_id not in forgery_by_author:
                        forgery_by_author[author_id] = []
                    forgery_by_author[author_id].append(img_path)
                except (ValueError, IndexError):
                    print(f"Skipping invalid forgery filename: {filename}")
                    continue



        print(f"Genuine authors: {len(genuine_by_author)}, {genuine_by_author.keys()}")
        print(f"Forgery authors: {len(forgery_by_author)}, {forgery_by_author.keys()}")
        for author_id, sigs in genuine_by_author.items():
            print(f"Author {author_id}: {len(sigs)} genuine signatures")
        for author_id, sigs in forgery_by_author.items():
            print(f"Author {author_id}: {len(sigs)} forged signatures")


        # Create pairs for each author
        for author_id in genuine_by_author:
            genuine_sigs = genuine_by_author.get(author_id, [])
            forged_sigs = forgery_by_author.get(author_id, [])
            if not (forged_sigs or genuine_sigs):
              print(f"Warning: No data found for author {author_id}")

            # Genuine-Genuine pairs (label = 1)
            for i in range(len(genuine_sigs)):
                for j in range(i + 1, len(genuine_sigs)):  # Pair different genuine samples
                    self.pairs.append((genuine_sigs[i], genuine_sigs[j]))
                    self.labels.append(1)

            # Genuine-Forgery pairs (label = 0)
            for genuine_sig in genuine_sigs:
                for forged_sig in forged_sigs:
                    self.pairs.append((genuine_sig, forged_sig))
                    self.labels.append(0)

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        # Get pair of image paths and label
        img1_path, img2_path = self.pairs[idx]
        label = self.labels[idx]

        # Load images
        img1 = Image.open(img1_path).convert('L')  # Grayscale, like FashionMNIST
        img2 = Image.open(img2_path).convert('L')

        # Apply transforms
        if self.transform:
            img1 = self.transform(img1)
            img2 = self.transform(img2)

        return img1, img2, torch.tensor(label, dtype=torch.float32)

# Example usage
transform = transforms.Compose([
    transforms.Resize((28, 28)),  # Resize to match FashionMNIST if needed
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))  # Standard normalization
])

dataset = SignatureVerificationDataset(
    genuine_dir=genuine_extract_path,
    forgery_dir=forgery_extract_path,
    transform=transform
)
dataloader = DataLoader(dataset, batch_size=1024, shuffle=True, num_workers=2)

# class CustomDataset(Dataset):
#     def __init__(self, data, targets):
#         self.X = data  # Already a tensor from torchvision
#         self.y = targets  # Already a tensor from torchvision
#         self.len = self.X.shape[0]

#     def __getitem__(self, index):
#         return self.X[index], self.y[index]

#     def __len__(self):
#         return self.len

# # Create CustomDataset instances
# traindata = CustomDataset(trainset.data.unsqueeze(1).float() / 255.0, trainset.targets)  # Normalize and add channel dimension
# testdata = CustomDataset(testset.data.unsqueeze(1).float() / 255.0, testset.targets)

# # Create DataLoaders
# trainloader = DataLoader(traindata, batch_size=512, shuffle=True)
# testloader = DataLoader(testdata, batch_size=512, shuffle=True, num_workers=2)


# classes = trainset.classes
# num_classes = 1
# num_input_channels = 1
# num_output_channels = 16
# image_size = dataset[0][0].shape[1]

# class Network(nn.Module):
#     def __init__(self):
#         super(Network, self).__init__()
#         self.flatten = nn.Flatten()
#         self.linear1 = nn.Linear(28 * 28, 16)
#         self.tanh = nn.Tanh()  # Using tanh as per your earlier query
#         self.linear2 = nn.Linear(16, 8)
#         self.tanh2 = nn.Tanh()  # Second tanh layer
#         self.linear3 = nn.Linear(8, 1)  # 10 classes for Fashion MNIST
#         self.softmax = nn.Softmax(dim=-1)
#         self.conv1 = nn.Conv2d(num_input_channels, num_output_channels, kernel_size=3, stride=1, padding=1)
#         self.relu = nn.ReLU()
#         self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
#         self.flatten = nn.Flatten()

#         self.fc = nn.Linear(num_output_channels * (image_size//2)**2, num_classes)

#     def forward(self, x):
#         x = self.conv1(x)
#         x = self.relu(x)
#         x = self.maxpool(x)
#         x = self.flatten(x)
#         x = self.fc(x)
#         return x

# # Initialize model, loss, and optimizer (using RMSProp as per your earlier query)
# model3 = Network()
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model3.parameters(), lr=0.001)  # RMSProp instead of SGD

# # Training loop
# num_epochs = 10
# epoch_loss = []

# for epoch in range(num_epochs):
#     train_loss = 0
#     for batch_X, batch_y in dataloader:
#         optimizer.zero_grad()
#         predicted = model3(batch_X)  # Forward pass
#         loss = criterion(predicted, batch_y)
#         loss.backward()  # Backpropagation
#         optimizer.step()  # Update weights
#         train_loss += loss.item()

#     # Calculate and store average loss for the epoch
#     average_loss = train_loss / len(dataloader)
#     epoch_loss.append(average_loss)
#     print(f'Epoch {epoch+1}, Loss: {average_loss:.4f}')

import torch.nn as nn

class SiameseCNN(nn.Module):
    def __init__(self):
        super(SiameseCNN, self).__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(64 * 5 * 5, 128)  # Adjust based on image size
        )

    def forward(self, x1, x2):
        embedding1 = self.cnn(x1)
        embedding2 = self.cnn(x2)
        return embedding1, embedding2

class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, emb1, emb2, label):
        cosine_sim = nn.functional.cosine_similarity(emb1, emb2)
        loss = label * (1 - cosine_sim) + (1 - label) * torch.clamp(cosine_sim - self.margin, min=0)
        return loss.mean()

# model = SiameseCNN()
# criterion = ContrastiveLoss(margin=0.2)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# num_epochs=10
# for epoch in range(num_epochs):
#     model.train()
#     for img1, img2, labels in dataloader:
#         optimizer.zero_grad()
#         emb1, emb2 = model(img1, img2)
#         loss = criterion(emb1, emb2, labels)
#         loss.backward()
#         optimizer.step()
#         print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

# # Save the model
# import torch
# torch.save(model.state_dict(), PATH)

# Load the model
model = SiameseCNN()
model.load_state_dict(torch.load(PATH))

import torch
import torch.nn.functional as F

# Define a threshold for classifying pairs
THRESHOLD = 0.5  # Tune this based on your dataset (e.g., via validation set)

def evaluate_accuracy(model, dataloader, threshold=0.5):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for img1, img2, labels in dataloader:
            # Get embeddings and cosine similarity
            emb1, emb2 = model(img1, img2)
            cosine_sim = F.cosine_similarity(emb1, emb2)

            # Predict based on threshold
            predictions = (cosine_sim > threshold).float()  # 1 if similar, 0 if dissimilar

            # Compare predictions with ground truth labels
            correct += (predictions == labels).sum().item()
            total += labels.size(0)

            # Optional: Print similarity and labels for debugging
            print(f"Cosine Similarity: {cosine_sim[:5]}")  # Print first 5 for brevity
            print(f"Ground Truth Labels: {labels[:5]}")
            print(f"Predictions: {predictions[:5]}")

    accuracy = correct / total
    return accuracy

if __name__ == '__main__':
    # Load the model
    model = SiameseCNN()
    model.load_state_dict(torch.load(PATH))

    # Evaluate accuracy
    accuracy = evaluate_accuracy(model, dataloader, THRESHOLD)
    print(f"Accuracy: {accuracy:.4f}")

